### ISSUE TITLE
Multi-gpu inference, the query gets stuck when using my own provider

### ISSUE THREAD

**Issue by Aaron-mindverse** [microsoft/DeepSpeed-MII#97]
I modified this file with my own defined provider. No problems with single cards, but query gets stuck with multiple cards. Here is the file I mainly modified.
"DeepSpeed-MII/mii/models/providers/huggingface.py"
![image](https://user-images.githubusercontent.com/115475227/201680825-3aad1c41-0ed8-49d2-9d45-8fcd642f9dfe.png)

Now it's stuck
![image](https://user-images.githubusercontent.com/115475227/201681187-b90608ed-67a9-42b9-b5ca-9f73f285d90c.png)

Here is my deepspeed version
![image](https://user-images.githubusercontent.com/115475227/201681852-a8b62de0-b710-45e9-af69-db2f8405a6ac.png)

**Comment by Aaron-mindverse** [comment]
> Hi @Aaron-mindverse it's not clear why your provider is hanging with multi-GPU. If you copy and paste the code (or provide a link to a branch with the modifications) I can test it on my side. But I would first recommend taking a look at our `BloomPipeline` and `load_hf_llm`:
> 
> https://github.com/microsoft/DeepSpeed-MII/blob/747072b08a94129eb1a5d88bbaffa574b7bf039f/mii/models/providers/llm.py#L25
> 
> Use this as a template for creating your `OPTProvider` and it should work with multi-GPU. Thanks!

Thank you so much, this worked for me, although I had to modify a lot of DeepSpeed code specifically tailored for the Bloom model, such as [get_transformer_name](https://github.com/microsoft/DeepSpeed/blob/21c28029648df4c98acd6331a8fdc0d29f297fa7/deepspeed/module_inject/replace_module.py#L124)
